### ISSUE TITLE
Stream from memory rather than file

### ISSUE THREAD

**Issue by Cap-n-Proud** [gluxon/node-mjpeg-server#2]
Hello, 

I just cam across this repository and it seems almost perfect. Would it be possible to modify the code to be used with in-memory image rather than a file?

I need to acquire an image from the raspberry camera, make some changes (ad overlay text, etc) and stream to a web browser. With reference to the example you provided.

Everything works fine if I do: 1) acquire, 2) save to file, 3) read, 4) call sendJPGData. However I would like to avoid disk access and use the data in memory: 1) acquire, 2) call sendJPGData 

In his case I got the following error:

_stream_writable.js:269
  var len = state.objectMode ? 1 : chunk.length;
                                        ^
TypeError: Cannot read property 'length' of undefined
    at writeOrBuffer (_stream_writable.js:269:41)
    at MjpegServer.Writable.write (_stream_writable.js:217:11)
    at sendJPGData (/home/pi/node-mjpeg-server/examples/server.js:56:21)
    at /home/pi/node-mjpeg-server/examples/server.js:42:2

**Comment by gluxon** [comment]
Glad you're enjoying it. It should work as long as your call to the `.write` method is a [Buffer](https://nodejs.org/api/buffer.html). Can you check and make sure `Buffer.isBuffer(myJPEGObject)` returns true?

**Comment by Cap-n-Proud** [comment]
Yes it it is a buffer.

I put my code on Github (https://github.com/pfnegrini/openCV-MJPEG-streamer.git). With reference to server.js:
row 44: I create a new buffer and fill with image =>  var toTransmit =""; toTransmit = new Buffer(im);  
row 46: test if it is a buffer (returns true) => console.log("Is it a buffer?", Buffer.isBuffer(toTransmit));
row 47: check length, well this is strange as it returns "undefined" =>  console.log("Lenght of buffer ", toTransmit.lenght);

If I try to use the new buffer in sendJPGData I still get the same error. Might it be a case of defining a special buffer? Any idea? 
Feel very close to the solution now...

**Comment by gluxon** [comment]
Hm.. what happens when you try changing this line:

``` javascript
toTransmit = new Buffer(im.toBuffer({ext: ".jpg", jpegQuality: 80}), "base64");
```

to this?:

``` javascript
toTransmit = im.toBuffer();
```

The undefined length on the buffer is interesting. Generally if you can `fs.write(fd, buffer)` the buffer, then the browser should also take it without a problem.

**Comment by Cap-n-Proud** [comment]
now it works! You can see the screenshot in my repository.
Only issue is the v4l2 video driver, when  start the server terminal reads:

```
VIDIOC_QBUF: Invalid argument
```

But the video goes smooth, after about 1700 frames video start lagging and at after a few hundreds frames the terminal reads:

```
libv4l2: error dequeuing buf: Resource temporarily unavailable
Killed
```

Any idea on how to fix it? 
Thank you very much your repository and suggestions helped to solve a long standing issue for me!

**Comment by gluxon** [comment]
My quick guess (could be totally wrong) is that the Node garbage collector may not be releasing all the jpgs fast enough. (MJPEG is actually a really inefficient video format.) Do you have a way of monitoring your process's memory and seeing how quickly it's growing? Or if it stays relatively stable?

P.S. Always glad to help.

**Comment by zeos** [comment]
Hi, what a great module! I was just testing with "v4l2camera" on my edison and all works well with fswebcam, uvc and v4l2camera nodejs tests,  but I got this error as a result, when trying to create a mjpeg server out of the raw jpg frames (loaded from memory) Any ideas? 
I am using NodeJS v4.4.3. Thank you!

```
Got request
isBuffer: true  Length: 118105
/home/zeos/cam.js:42
                mjpegReqHandler.write(data, function() {
                                ^

TypeError: mjpegReqHandler.write is not a function
    at sendJPGData (/home/zeos/cam.js:42:19)
    at Camera.loop (/home/zeos/cam.js:34:3)
```

**Comment by gluxon** [comment]
@zeos Can you post more code? How is `mjpegReqHandler` being created?

**Comment by zeos** [comment]
here we go, very simple code, perhaps, I have an error somewhere else. Thanks for review it!

```
cam.start();

http.createServer(function(req, res) 
{
    console.log("Got request");

    mjpegReqHandler = mjpegServer.createReqHandler(req, res);


    var i = 0;
    var should_capture =  true;

    cam.capture(function loop() {

        var img = cam.frameRaw();
        var data = Buffer(img);
        console.log('isBuffer:', Buffer.isBuffer(data),' Length:', data.length);

        sendJPGData(data);
        i++;
        if(should_capture) cam.capture(loop);
    });


    function sendJPGData(data) 
    {
        mjpegReqHandler.write(data, function() {

            checkIfFinished();      
        });
    }


    function checkIfFinished() {
    if (i > 100) {
      //clearInterval(timer);
      should_capture = false;
      mjpegReqHandler.close();
      console.log('End Request');
    };



  }


}).listen(8081);
```

**Comment by gluxon** [comment]
I'm not sure what's causing `mjpegReqHandler` to change or be cleared. Can you trace it throughout the execution of your program? Perhaps in a debugger or just printing it out every step?

If `mjpegServer.createReqHandler(req, res)` isn't returning a streams object, then there might be a bigger environment/setup issue.

**Comment by gluxon** [comment]
Going to close this for now. Please reopen if more information comes up.
