### ISSUE TITLE
Output appears cropped in VLC?

### ISSUE THREAD

**Issue by RobertSmart** [gluxon/node-mjpeg-server#3]
Hi,

Thanks for the library, its been really useful to quickly create a mjpg stream. There is one odd thing though. If I open the output stream in vlc,  the video is zoomed and cropped. If you do it the example you'll see that the numbers appear much nearer the bottom right corner than if you open the stream in a browser. I investigated if it was a setting in VLC but I don't think it is? Does the stream have to specifiy dimensions or something that might be getting set properly?

Any ideas?

Thanks

**Comment by gluxon** [comment]
It seems to be playing in VLC for me. I don't see any zooming or cropping, and numbers are centered. Can you try another machine? What are your current machine's specifications?

**Comment by RobertSmart** [comment]
Hi,

You are correct.
I have tried it on another version of VLC on a tablet and it appears fine. It must be a bug, or a hidden setting in that version of VLC. 
Thanks
