### ISSUE TITLE
Is this missing a close handler?

### ISSUE THREAD

**Issue by wmertens** [gluxon/node-mjpeg-server#6]
Hi, I would like to send an mjpeg stream based on this module, working like this:

* at server start, begin fetching images from camera, make eventEmitter for "new image"
* when client connects to `/live`, create mjpeg stream, and subscribe to "new image" notifications
* when the client disconnects, unsubscribe and release objects for garbage collection

Very simple, however, I wonder what happens when the client disconnects? I don't see an `on('close')` handler on the response? I suppose the `mjpegServer` could take an extra callback for when the client quits?

**Comment by gluxon** [comment]
This library accepts `req` and `res` objects from a server library, so HTTP related events will be fired from those objects. If you're using the built-in Node.js http module, I believe you can listen to the `abort` event on the `req` object you pass into the `mjpeg-server` stream.

As for stopping the mjpeg fetching, there's likely a pause function you can call for the library you're using there. Let me know if this doesn't help. Good luck. 👍

**Comment by wmertens** [comment]
Aha indeed, I simply had to add a handler for `res.on('close')`, thanks!

I noticed that you are storing `req` on `this`, but not using it. This way, you prevent it from being GCed…

**Comment by gluxon** [comment]
> I noticed that you are storing req on this, but not using it. This way, you prevent it from being GCed…

Good catch. Would you be willing to submit a pull request? I can do it quickly, but wanted to give you a chance since you found the issue and contributions to other projects always look good on a GitHub profile.

**Comment by wmertens** [comment]
Done in #8 :) I'll close this one, because it's not really related.
