### ISSUE TITLE
DeprecationWarning node v16.4.0

### ISSUE THREAD

**Issue by stephenjg24-git** [gluxon/node-mjpeg-server#9]
When I launch appium I am getting this message.

(node:6668) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/......./.nvm/versions/node/v16.4.0/lib/node_modules/appium/node_modules/mjpeg-server/package.json' of './lib/mpegserver'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

I then ran ..... this is the package with in appium

node --trace-deprecation /Users/stephen.lichtenberg/.nvm/versions/node/v16.4.0/lib/node_modules/appium/node_modules/mjpeg-server
(node:6772) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/......./.nvm/versions/node/v16.4.0/lib/node_modules/appium/node_modules/mjpeg-server/package.json' of './lib/mpegserver'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:358:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:560:18)
    at resolveMainPath (node:internal/modules/run_main:15:25)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:73:24)
    at node:internal/main/run_main_module:17:47

I then  installed the package outside of the appium packages. 

node --trace-deprecation /Users/........./.nvm/versions/node/v16.4.0/lib/node_modules/mjpeg-server
(node:6903) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/stephen.lichtenberg/.nvm/versions/node/v16.4.0/lib/node_modules/mjpeg-server/package.json' of './lib/mpegserver'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:358:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:560:18)
    at resolveMainPath (node:internal/modules/run_main:15:25)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:73:24)
    at node:internal/main/run_main_module:17:47

**Comment by gluxon** [comment]
Hi @stephenjg24-git, I'll take a look and get a fix out. Thanks for the detailed report!

**Comment by gluxon** [comment]
Release `0.3.1` should not have this issue. Thanks again for reporting!

**Comment by stephenjg24-git** [comment]
thanks for so quickly addressing this,

I installed the package local npm i mjpeg-server. Then ran the node --trace-deprecation /Users/........./.nvm/versions/node/v16.4.0/lib/node_modules/mjpeg-server.  command again.

The issue is resolved.

Have a great day
